export const menu = [
  {
    id: 1,
    title: "View My Top Artists",
    url: "/",
    icon: "user.svg",
  },
  {
    id: 2,
    title: "View My Top Tracks",
    url: "/",
    icon: "product.svg",
  },
  {
    id: 3,
    title: "Artist Fusion",
    url: "/",
    icon: "form.svg",
  },
];

export const tracks = [
  {
    id: 1,
    image: "/noavatar.png",
    title: "Troubled waters",
    artist: "Chris brown",
    album: "Indigo",
    duration: "3:15",
  },
  {
    id: 2,
    image: "/noavatar.png",
    title: "BS",
    artist: "Jhene Aiko, H.E.R",
    album: "Chilombo",
    duration: "3:09",
  },
  {
    id: 3,
    image: "/noavatar.png",
    title: "Lonely at the top",
    artist: "Asake",
    album: "Work of Art",
    duration: "3:15",
  },
  {
    id: 4,
    image: "/noavatar.png",
    title: "Check",
    artist: "kojo funds, RAYE",
    album: "Check-single",
    duration: "3:38",
  },
  {
    id: 5,
    image: "/noavatar.png",
    title: "Play play",
    artist: "J hus, Burna boy",
    album: "Big Conspiracy",
    duration: "3:27",
  },
  {
    id: 6,
    image: "/noavatar.png",
    title: "Is There Someone Else?",
    artist: "The Weeknd",
    album: "Dawn FM",
    duration: "3:20",
  },
  {
    id: 7,
    image: "/noavatar.png",
    title: "Rock Steady",
    artist: "The Whispers",
    album: "Just gets better with time",
    duration: "4:27",
  },
  {
    id: 8,
    image: "/noavatar.png",
    title: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
    duration: "3:23",
  },
  {
    id: 9,
    image: "/noavatar.png",
    title: "Collateral Damage",
    artist: "Burna boy",
    album: "African Giant",
    duration: "3:08",
  },
  {
    id: 10,
    image: "/noavatar.png",
    title: "Many Men",
    artist: "50 Cent",
    album: "Get Rich or Die Tryin'",
    duration: "3:30",
  },
  {
    id: 11,
    image: "/noavatar.png",
    title: "Fair trade",
    artist: "Drake ft Travis Scott",
    album: "Certified Lover Boy",
    duration: "2:57",
  },
  {
    id: 12,
    image: "/noavatar.png",
    title: "A thousand times",
    artist: "Post Malone",
    album: "Hollywood's bleeding",
    duration: "3:17",
  },
  {
    id: 12,
    image: "/noavatar.png",
    title: "Too experienced",
    artist: "Barrington Levy",
    album: "GRELCD507",
    duration: "3:22",
  },
];

export const recoArtists = [
  {
    id: 1,
    image: "/noavatar.png",
    artist: "Burna boy",
  },
  {
    id: 2,
    image: "/noavatar.png",
    artist: "Arya Star",
  },
  {
    id: 3,
    image: "/noavatar.png",
    artist: "Sauti Sol",
  },
  {
    id: 4,
    image: "/noavatar.png",
    artist: "Sean Paul",
  },
];

export const recoTracks = [
  {
    id: 1,
    image: "/noavatar.png",
    title: "I want you",
    artist: "Bien",
  },
  {
    id: 2,
    image: "/noavatar.png",
    title: "Temperature",
    artist: "Sean Paul",
  },
  {
    id: 3,
    image: "/noavatar.png",
    title: "Tested,Approved & Trusted",
    artist: "Burna boy",
  },
  {
    id: 4,
    image: "/noavatar.png",
    title: "We Caa Done",
    artist: "Popcaan ft Drake",
  },
  {
    id: 5,
    image: "/noavatar.png",
    title: "Charm",
    artist: "Rema",
  },
  {
    id: 6,
    image: "/noavatar.png",
    title: "Foreplay",
    artist: "Shenseea",
  },
  {
    id: 7,
    image: "/noavatar.png",
    title: "I want you",
    artist: "Bien",
  },
  {
    id: 8,
    image: "/noavatar.png",
    title: "It is what it is",
    artist: "Adenkule Gold",
  },
  {
    id: 9,
    image: "/noavatar.png",
    title: "I'll kill you",
    artist: "Summer Walker, Jhene Aiko",
  },
];
